### PR TITLE
PHP 7 Memcached: fix calling `Memcached::getMultiple`

### LINKED ISSUE #16: Memcached: using the API incorrectly
[`php7--fix-get-multi-bug`](https://github.com/iFixit/Matryoshka/compare/php7--fix-get-multi-bug)

We received this error:

```
Memcached::getMulti() expects at most 2 parameters, 3 given in
library/iFixit/Matryoshka/Memcached.php on line 80
```

Make a test that exposes this and fix it.

### PR DESCRIPTION
**Pull request by davidrans**
At the time of this writing, the PHP 7 branch of the memcached client
has a slightly different API than `master`. `getMulti()` takes 2
arguments instead of 3 (it's missing the second `$cas_tokens` argument).

We want Matryoshka to work with both PHP 7 and PHP 5 clients, and this
is the cleanest solution we could think of.

Closes #16

### CODE REVIEW

**Comment by danielbeardsley** [comment]
CR :+1: Thanks!

**Comment by kwiens** [comment]
My suggestions are trivial — run with them if you want.

CR 👍 
dev_block 🚨  almost

File: library/iFixit/Matryoshka/Memcached.php [hunk 1]
```diff
@@ -6,6 +6,10 @@
 
 class Memcached extends Backend {
    const MAX_KEY_LENGTH = 250;
+
+   // Is using instance of Memcache whose `getMulti` only accepts two args.
+   protected static $isPHP7 = null;
```
Comment (danielbeardsley) [inline library/iFixit/Matryoshka/Memcached.php]: Fixed

File: library/iFixit/Matryoshka/Memcached.php [hunk 2]
```diff
@@ -18,6 +22,22 @@ public static function isAvailable() {
...
+         $getMulti = new \ReflectionMethod($memcached, 'getMulti');
+         $numArgs = $getMulti->getNumberOfParameters();
+
+         if ($numArgs === 2) {
+            self::$isPHP7 = true;
+         } else {
+            self::$isPHP7 = false;
+         }
+      }
+
```
Comment (danielbeardsley) [inline library/iFixit/Matryoshka/Memcached.php]: Fixed

**Comment by danielbeardsley** [comment]
CR 👍  un_dev_block 👍

**Comment by danielbeardsley** [comment]
Derp, missed a usage of the variable during the rename.  All better. CR 👍

File: library/iFixit/Matryoshka/Memcached.php [hunk 3]
```diff
@@ -18,6 +22,19 @@ public static function isAvailable() {
...
     */
    public static function create(\Memcached $memcached) {
+      // The PHP 7 version of Memcached has a different API. We can tell which
+      // API to use by how many arguments the method takes.
+      if (self::$getMultiHasTwoParams === null) {
+         $getMulti = new \ReflectionMethod($memcached, 'getMulti');
+         $numArgs = $getMulti->getNumberOfParameters();
+
+         if ($numArgs === 2) {
+            self::$getMultiHasTwoParams = true;
```
Comment (davidrans) [inline library/iFixit/Matryoshka/Memcached.php]: You're right, that's better! a11e91b

**Comment by kwiens** [comment]
CR 😆

**Comment by danielbeardsley** [comment]
CR 👍
